apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns-argocd.yaml
  - ns-cert-manager.yaml
  - ns-cnpg-system.yaml
  - ns-external-dns.yaml
  - ns-longhorn.yaml
  - ns-metallb-system.yaml
  - ns-monitoring.yaml
  - ns-nfs-provisioner.yaml
  - ns-nginx-ingress.yaml
  - ns-step-issuer.yaml
