# CHANGEME
nfs:
  server: 10.0.0.2
  path: /mnt/user/k8s

storageClass:
  create: true
  name: nfs
  defaultClass: false
  reclaimPolicy: Delete
  allowVolumeExpansion: true
  archiveOnDelete: true
  accessModes: ReadWriteMany
  volumeBindingMode: Immediate

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
